### ISSUE TITLE
Support for non-atomistic force fields

### ISSUE THREAD

**Issue by summeraz** [iModels/foyer#40]
The current implementation of foyer requires an element name for all particles.  This is inferred from the particle's name, such that if a particle has a name that does not match an existing element, an error occurs when `element = elem.Element.getBySymbol(mb_particle.name)` is executed.  Would there be a way to generalize foyer such that any name could be provided for the "element" attribute?  For example, if I had a box of Lennard-Jones particles, is there a way I could set their "element" to "LJ", or set the element of united-atom alkanes to "CH2" and "CH3"?

**Comment by ctk3b** [comment]
I think an easy way would be to add an optional flag to [this](https://github.com/iModels/foyer/blob/master/foyer/forcefield.py#L24-L74) that dictates whether elements should be assigned or the name taken as is.

**Comment by summeraz** [comment]
It could be as easy as changing
`element = elem.Element.getBySymbol(mb_particle.name)`
to
`try:
    element = elem.Element.getBySymbol(mb_particle.name)
except KeyError:
    element = mb_particle.name`

From some quick testing it looks that openmm Atoms can have arbitrary element names.

**Comment by summeraz** [comment]
We could include a flag in the except block that raises a warning after the topology has been built that warns the user that the element names for some particles could not be interpreted

**Comment by ctk3b** [comment]
That should also be ok. Make sure you actually create a new OpenMM Atom object though instead of just using the string.

Also I would recommend adding a little cache like [here](https://github.com/iModels/mbuild/blob/master/mbuild/compound.py#L844-L853) so that the user doesn't get spammed with warnings for every instance of a missing atom name.

**Comment by summeraz** [comment]
Any ideas on how to load a force field with atomtypes that contain non-periodic table element names?   I think I've almost got it working if I can figure that part out.

It looks like atomtypes are loaded using [this function](https://github.com/iModels/foyer/blob/master/foyer/forcefield.py#L110-L122), which calls a function of the same name in OpenMM.  Currently if an atomtype is not one of those in the periodic table, then a KeyError is generated when a periodic table look-up is attempted by OpenMM.

My current line of thinking is doing something like this
```
def registerAtomType(self, parameters):
    actual_element = parameters['element']
    parameters['element'] = 'H'
    super(Forcefield, self).registerAtomType(parameters)
    # Somehow access the atomtype we just loaded in and change the element name to actual_element
```
I'm just not sure how to access the atomtype that has just been loaded to change the element name.

**Comment by ctk3b** [comment]
This is the [OpenMM function](https://github.com/pandegroup/openmm/blob/9f717609213a36aa350a43f352786acf892a49b0/wrappers/python/simtk/openmm/app/forcefield.py#L340-L359) where that happens. You can either replicate this function entirely on our end and remove the `super()` or see if you can edit `self._atomTypes` and change the name of the specific one after creation.

**Comment by summeraz** [comment]
Cool, yeah it looks like editing `self._atomTypes[parameters'name'].element` should do the trick

**Comment by ctk3b** [comment]
Preliminarily implemented
